import m  from "./img/teams_m.png";
import m1 from "./img/teams_m1.png";
import m2 from "./img/teams_m2.png";
import m3 from "./img/teams_m3.png";
import m4 from "./img/teams_m4.png";
import m5 from "./img/teams_m5.png";
import m6 from "./img/teams_m6.png";
import m7 from "./img/teams_m7.png";
import m8 from "./img/teams_m8.png";
import star from "./img/icon_star.svg";
import team from './img/team.jpg';
import upload_c from "./img/upload_c.png";
import upload_s from "./img/upload_s.png";
export default {m,m1,m2,m3,m4,m5,m6,m7,m8,star,team,upload_c,upload_s};