import m1 from "./img/teams_member1.png";
import m2 from "./img/teams_member2.png";
import m3 from "./img/teams_member3.png";
import m4 from "./img/teams_member4.png";
import m5 from "./img/teams_member5.png";
import m6 from "./img/teams_member6.png";
import m7 from "./img/teams_member7.png";
import m8 from "./img/teams_member8.png";
import star from "./img/icon_star.svg";
import team from './img/team.jpg';
import upload_c from "./img/upload_c.png";
import upload_s from "./img/upload_s.png";
export default {m1,m2,m3,m4,m5,m6,m7,m8,star,team,upload_c,upload_s};